spring:
  application:
    name: todoapp
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 8080
  servlet:
    context-path: /api/v1
logging:
  level:
    root: INFO
    org:
      springframework: INFO
